apiVersion: v1
kind: ServiceAccount
metadata:
  name: ids-sa
  namespace: ids
  annotations:
    # Workload Identity — bind to GCP service account
    iam.gke.io/gcp-service-account: ids-inference@YOUR_PROJECT.iam.gserviceaccount.com
