apiVersion: v1
kind: Service
metadata:
  name: ids-inference-svc
  namespace: ids
spec:
  type: ClusterIP
  selector:
    app: ids-inference
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
